# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/freedom/Desktop/Single_Clock_Cycle_CPU/CPU_showALUres/CPU1.srcs/sources_1/ip/irom_1/irom.xci
# IP: The module: 'irom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/freedom/Desktop/Single_Clock_Cycle_CPU/CPU_showALUres/CPU1.srcs/sources_1/ip/irom_1/irom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/freedom/Desktop/Single_Clock_Cycle_CPU/CPU_showALUres/CPU1.srcs/sources_1/ip/irom_1/irom.xci
# IP: The module: 'irom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/freedom/Desktop/Single_Clock_Cycle_CPU/CPU_showALUres/CPU1.srcs/sources_1/ip/irom_1/irom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
